spring:
  application:
    name: commende-service

server:
  port: 8084

spring.datasource:
  url: jdbc:mysql://localhost:3306/bd-commande?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
  username: root
  password: 09132339Aa

spring.jpa:
  show-sql: true
  hibernate.ddl-auto: update
  dialect: org.hibernate.dialect.MySQL8Dialect

security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: http://localhost:8080/realms/Gestion-Cafiteria-ms

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
